[package]
name = "brutal-nginx-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
nginx-sys = {git="https://github.com/nginx/ngx-rust.git", features=["stream"]}
ngx =  {git="https://github.com/nginx/ngx-rust.git"}

[features]
default = [
    "export-modules",
    # Enables the build scripts to build a copy of nginx source and link against it.
    "ngx/vendored",
]
# Generate `ngx_modules` table with module exports
# The exports table is required for building loadable modules with --crate-type cdylib
# outside of the NGINX buildsystem. However, cargo currently does not detect
# this configuration automatically.
# See https://github.com/rust-lang/rust/issues/20267
export-modules = []
linux = []

[lib]
name = "ngx_brutal_rs_module"
crate-type = ["cdylib"]

[profile.release]
strip = true 
opt-level = "z"
lto = true
codegen-units = 1
