ARG NGX_VERSION=1.28.3
# NGINX official images are available for one specific release of Debian,
# e.g `nginx:1.28.3-trixie`. Please see the list of tags on Docker Hub
# if you need to change NGX_VERSION.
ARG DEBIAN_RELEASE=trixie

# --- builder: build all examples
FROM rust:slim-${DEBIAN_RELEASE} AS build
ARG NGX_VERSION
ARG NGX_CONFIGURE_ARGS=
WORKDIR /project
RUN --mount=type=cache,target=/var/cache/apt <<EOF
    set -eux
    export DEBIAN_FRONTEND=noninteractive
    apt-get -qq update
    apt-get -qq install --yes --no-install-recommends --no-install-suggests \
        libclang-dev \
        libpcre2-dev \
        libssl-dev \
        zlib1g-dev \
        pkg-config \
        git \
        grep \
        gawk \
        gnupg2 \
        sed \
        make
    git config --global --add safe.directory /project
EOF

COPY . .

RUN --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    cargo fetch --locked

RUN --mount=type=cache,id=target,target=target \
    --mount=type=cache,id=cache,target=.cache \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    mkdir -p /out && \
    cargo build --release && cargo build && \
    mv /project/target/release/libngx_brutal_rs_module.so /out/ngx_brutal_rs_module.so && \
    mv /project/target/debug/libngx_brutal_rs_module.so /out/debug_ngx_brutal_rs_module.so


FROM scratch AS export
COPY --from=build /out /
